
name: Automated-Build

on:
  workflow_dispatch:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]


jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Compile
      run: |
        make
    - name: make package and list files
      run: |
       ls
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"


    - name: copy installer For Release
      run: |
        cp FMCBInstaller.elf __Release/
             
    - name: zip Folder For Release
      run: |
         cd __Release
         zip -r FreeMcBoot-1.966-Installer-isra.zip *
         cd ..
         echo ------------------- root
         ls
         echo ------------------- release
         ls __Release
        
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: FMCBinstaller-${{ steps.slug.outputs.sha8 }}
        path: |
            *.zip

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest automated compilation and repack"
        files: |
               *.zip
