
name: Build [1966]

on:
  workflow_dispatch:
  push:
    paths:
      - '1966/*.*'
      - '.github/workflows/compile-1966.yml'
  pull_request:
  repository_dispatch:
    types: [run_build]


jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Compile
      run: |
        cd 1966
        make
        
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"


    - name: copy installer For Release
      run: |
        cd 1966
        cp FMCBInstaller.elf __Package/
        SCH=${GITHUB_SHA::7}
        cd __Package
        cd lang
        echo $SCH >commit.txt
        cd ..
        cd ..
        cd ..
             
    - name: zip Folder For Release
      run: |
         cd 1966
         cd __Package
         cd INSTALL
         mkdir APPS-HDD
         cd ..
         cd ..
         DATEE=`date '+[%Y-%m-%d]'`
         mv __Package FMCBinstaller$DATEE
         zip -r FMCB-1966.zip FMCBinstaller*/*
        
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: FMCBinstaller-1966-isra-${{ steps.slug.outputs.sha8 }}
        path: |
            1966/*.zip

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-1966"
        title: "Latest release [1.966]"
        files: |
               1966/*.zip
               
