name: Update dependencies

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Component_update]
  schedule:
    - cron: "0 15 1 * *"
jobs:
  download-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update wLaunchELF_ISR 
      run: |        
         wget https://github.com/israpps/wLaunchELF_ISR/releases/download/latest/BOOT-EXFAT.ELF -O $PWD/BOOT.ELF
         echo -- 1.966
         cp $PWD/BOOT.ELF installer_res/1966/INSTALL/BOOT/BOOT.ELF
         cp $PWD/BOOT.ELF installer_res/1966/INSTALL/BOOT-HDD/BOOT.ELF
         echo -- 1.965
         cp $PWD/BOOT.ELF installer_res/1965/INSTALL/BOOT/BOOT.ELF
         cp $PWD/BOOT.ELF installer_res/1965/INSTALL/BOOT-HDD/BOOT.ELF
         echo -- 1.964
         cp $PWD/BOOT.ELF installer_res/1964/INSTALL/BOOT/BOOT.ELF
         cp $PWD/BOOT.ELF installer_res/1964/INSTALL/BOOT-HDD/BOOT.ELF
         echo -- 1.963
         cp $PWD/BOOT.ELF installer_res/1963/INSTALL/BOOT/BOOT.ELF
         cp $PWD/BOOT.ELF installer_res/1963/INSTALL/BOOT-HDD/BOOT.ELF
         echo -- 1.953
         cp $PWD/BOOT.ELF installer_res/1953/INSTALL/BOOT/BOOT.ELF
         cp $PWD/BOOT.ELF installer_res/1953/INSTALL/BOOT-HDD/BOOT.ELF
         echo -- apps
         mv $PWD/BOOT.ELF MASS/APPS/ULE_ISR/ULE_ISR.ELF

    - name: Update wLaunchELF
      run: |
           wget https://github.com/ps2homebrew/wLaunchELF/releases/download/latest/BOOT.ELF -O MASS/APPS/ULE_LATEST/ULE_LATEST.ELF

    - name: Update wLaunchELF_ISR_HDD
      run: |
           wget https://github.com/israpps/wLaunchELF_ISR_HDD/releases/download/latest/ULE_ISR_HDD.ELF -O $PWD/ULE_ISR_HDD.ELF
           cp $PWD/ULE_ISR_HDD.ELF MASS/APPS/ULE_ISR_HDD/ULE_ISR_HDD.ELF
           cp $PWD/ULE_ISR_HDD.ELF installer_res/1966/INSTALL/BOOT-HDD/ULE_ISR_HDD.ELF
           mv $PWD/ULE_ISR_HDD.ELF installer_res/1965/INSTALL/BOOT-HDD/ULE_ISR_HDD.ELF
           mv $PWD/ULE_ISR_HDD.ELF installer_res/1964/INSTALL/BOOT-HDD/ULE_ISR_HDD.ELF
           mv $PWD/ULE_ISR_HDD.ELF installer_res/1963/INSTALL/BOOT-HDD/ULE_ISR_HDD.ELF
           mv $PWD/ULE_ISR_HDD.ELF installer_res/1953/INSTALL/BOOT-HDD/ULE_ISR_HDD.ELF

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Update uLaunchELF versions'
